version: '3.5'
services:

  # The Application
  dumbo-app:
    container_name: dumbo-app
    image: dumbo-app
    build:
      context: ./
      dockerfile: docker/application/Dockerfile
      args:
        - XDEBUG_REMOTE_ENABLE=${XDEBUG_REMOTE_ENABLE}
        - XDEBUG_REMOTE_AUTOSTART=${XDEBUG_REMOTE_AUTOSTART}
        - XDEBUG_PROFILER_ENABLE=${XDEBUG_PROFILER_ENABLE}
    working_dir: /var/www
    ports:
      - 9002:9000
    networks:
      - dumbo
    volumes:
      - ./:/var/www
    depends_on:
      - mysql
    environment:
      - "DB_DATABASE=homestead"
      - "DB_USERNAME=homestead"
      - "DB_HOST=mysql"
      - "DB_PASSWORD=banana500"
      - "KAFKA_BROKERS=kafka"
      - "REDIS_HOST=dumbo-redis"
      - "APP_URL=http://localhost:8084"
      - "CACHE_DRIVER=redis"
      - "KAFKA_CONSUMER=dumbo-app-local"
      - "XDEBUG_CONFIG=remote_host=host.docker.internal"
      - "PHP_IDE_CONFIG=serverName=dumbo"

  # The Web Server
  dumbo-web:
    container_name: dumbo-web
    image: dumbo-web
    build:
      context: ./
      dockerfile: docker/web/Dockerfile
    working_dir: /var/www
    depends_on:
      - dumbo-app
    networks:
      - dumbo
    volumes:
      - ./public:/var/www/public
    ports:
      - 8084:80

  # The Database
  mysql:
    container_name: mysql
    networks:
      - dumbo
    image: mysql:5.7
    volumes:
      - dumbo-db:/var/lib/mysql
    environment:
      - "MYSQL_ROOT_PASSWORD=banana500"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=banana500"
      - "MYSQL_DATABASE=homestead"
    ports:
      - 33065:3306

  # Redis
  dumbo-redis:
    container_name: dumbo-redis
    networks:
      - dumbo
    image: redis:latest
    ports:
      - 6370:6370

volumes:
  dumbo-db:

networks:
  dumbo:
    name: dumbo
